### PR TITLE
Changes for HA support

### PR DESCRIPTION
**Pull request by srijanmishra**
The pull request has all the changes required for HA support in rfproxy.
The changes include processing of new master election message sent by RFMonitor and inform about the newly elected master to all the devices connected.

### CODE REVIEW

**Comment by joestringer** [comment]
I'm not particularly happy with the merging and patches c467190 and 0e43f62. It looks like you took your older branch, merged the newer branch in, then continued work. This is unnecessary; just base your newer patches on the 'ha' branch.

If there is actually problem in the github/routeflow/ha branch, please create a patch to fix it. The later patches can then be rebased on top. 

I would expect the history to look like:
_current routeflow 'ha' branch_
_any fixes for the routeflow 'ha' branch_
5d852f7
9063ab7
31944c7

EDIT: You can see clearly what I mean at the network graph: https://github.com/routeflow/ryu-rfproxy/network

From vandervecken, there is the routeflow/ha branch with two patches.
From vandervecken, there is the srijanmishra/ha branch with (almost the same) two patches, followed by two merge commits to resolve the differences. srijanmishra/submit/ha then adds 3 more patches on top. You should be able to rebase the top 3 patches from srijanmishra/submit/ha directly against routeflow/ha.

**Comment by srijanmishra** [comment]
I have rebased my branch to have commits as you mentioned. 
But it seems that your comments on this pull request are lost due to the rebasing.

EDIT: The rebasing has changed the commit sha but the commits are same. Will it be a problem?
I have all the comments you have and will fix the addressed issues.

**Comment by joestringer** [comment]
The fact that GitHub loses the original comments is why I like the idea of making a fresh pull request each time you address feedback and change the tree. You can see why now :-)

Overall these changes look fine to me.

**Comment by joestringer** [comment]
It looks like this pull request is superceded by #5. Closing.

**Pull request closed without merging**
