### PR TITLE
Restrict slave controller.

### PR DESCRIPTION
**Pull request by srijanmishra**
As the slave controller instances was also receiving route updates from rfserver and trying to push them into device so made following changes

1) Restricted slave controller instances from sending route updates to device,
2) Restricted slave controller from updating table entries.

### CODE REVIEW

**Comment by joestringer** [comment]
I squashed these patches and applied the patch with the following incrementals:-

```
diff --git a/rfproxy.py b/rfproxy.py                                                                                                                                            
index dd8ca3d..90945f0 100755                                               
--- a/rfproxy.py                                                            
+++ b/rfproxy.py                                                            
@@ -104,7 +104,6 @@ datapaths = Datapaths()                                 
 class RFProcessor(IPC.IPCMessageProcessor):                                
     def process(self, from_, to, channel, msg):                            
         type_ = msg.get_type()                                             
-        #restrict all slaves from sending message to the device            
         if type_ == ROUTE_MOD and CONF.ofp_role != 'slave':                
             dp = datapaths.get(msg.get_id())                               
             ofmsg = create_flow_mod(dp, msg.get_mod(), msg.get_matches(),  
@@ -118,8 +117,6 @@ class RFProcessor(IPC.IPCMessageProcessor):             
             else:                                                          
                 log.info("ofp_flow_mod was sent to datapath (dp_id = %s)", 
                                  msg.get_id())                             
-                                                                           
-        # restrict slave from updating table entries                       
         if type_ == DATA_PLANE_MAP:                                        
             table.update_dp_port(msg.get_dp_id(), msg.get_dp_port(),       
             msg.get_vs_id(), msg.get_vs_port())                            
@@ -136,6 +133,7 @@ class RFProxy(app_manager.RyuApp):                      
         super(RFProxy, self).__init__(*args, **kwargs)                     

         ID = 0                                                             
+        self.role = parse_role_request(CONF.ofp_role, dp)                  
         self.ipc = MongoIPC.MongoIPCMessageService(MONGO_ADDRESS,          
                                                    MONGO_DB_NAME, str(ID), 
                                                    hub_thread_wrapper,     
@@ -150,7 +148,6 @@ class RFProxy(app_manager.RyuApp):                      
         dp = ev.dp                                                         
         dpid = dp.id                                                       
         ports = dp.ports                                                   
-        self.role = parse_role_request(CONF.ofp_role, dp)                  
         send_role_request(self.role, dp)                                   
         if ev.enter:                                                       
             log.info("Datapath is up (dp_id=%s)", dpid_to_str(dpid))
```

**Comment by srijanmishra** [comment]
The second last change that is refactoring of
`self.role = parse_role_request(CONF.ofp_role, dp)`
breaks the code as the parameter dp is not available is not present in the context of current function.

**Comment by joestringer** [comment]
Ah, I apologise, that was a bit sloppy of me. My concern was that the next round of changes will allow another component to change the role via IPC, and it seems strange to pull from the CONF (ie, commandline parameters) each time. I propose the following fix:-

```
diff --git a/rfproxy.py b/rfproxy.py                                                                                                    
index 90945f0..01df621 100755                                               
--- a/rfproxy.py                                                            
+++ b/rfproxy.py                                                            
@@ -133,7 +133,7 @@ class RFProxy(app_manager.RyuApp):                      
         super(RFProxy, self).__init__(*args, **kwargs)                     

         ID = 0                                                             
-        self.role = parse_role_request(CONF.ofp_role, dp)                  
+        self.role = CONF.ofp_role                                          
         self.ipc = MongoIPC.MongoIPCMessageService(MONGO_ADDRESS,          
                                                    MONGO_DB_NAME, str(ID), 
                                                    hub_thread_wrapper,     
@@ -148,7 +148,8 @@ class RFProxy(app_manager.RyuApp):                      
         dp = ev.dp                                                         
         dpid = dp.id                                                       
         ports = dp.ports                                                   
-        send_role_request(self.role, dp)                                   
+        ofp_role = parse_role_request(self.role, dp)                       
+        send_role_request(ofp_role, dp)                                    
         if ev.enter:                                                       
             log.info("Datapath is up (dp_id=%s)", dpid_to_str(dpid))       
             datapaths.register(dp)
```

**Comment by srijanmishra** [comment]
Yes this looks good. Will you commit it or should I commit send a pull request?

**Comment by joestringer** [comment]
I can send it through.

**Pull request closed without merging**
