### PR TITLE
Create IPCMessageService via the new, abstract factory

### PR DESCRIPTION
**Pull request by mzero**
Change the rfpoxy to support the new API for creating an IPC service. This is required to use the ZeroMQ based IPC mechanism. See the corresponding pull request for RouteFlow.

### CODE REVIEW

**Comment by joestringer** [comment]
I'm getting the below exception running this new code.

```
loading app rfproxy                                                         
loading app ryu.controller.ofp_handler                                                                                                  
creating context dpset                                                      
instantiating app ryu.controller.ofp_handler                                
instantiating app rfproxy                                                   
Exception in thread ipc-main-worker:                                        
Traceback (most recent call last):                                          
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner    
    self.run()                                                              
  File "/usr/lib/python2.7/threading.py", line 763, in run                  
    self.__target(*self.__args, **self.__kwargs)                            
  File "/home/switch/git/RouteFlow/rflib/ipc/ZeroMQIPC.py", line 79, in _main_worker
    ready = dict(poller.poll())                                             
  File "/home/switch/git/RouteFlow/rflib/ipc/eventlet_green_zmq_missing.py", line 55, in poll
    select.select(rlist, wlist, xlist, timeout)                             
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/select.py", line 75, in select
    listeners.append(hub.add(hub.READ, k, on_read))                         
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/epolls.py", line 48, in add
    listener = BaseHub.add(self, evtype, fileno, cb)                        
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 126, in add
    evtype, fileno, evtype))                                                
RuntimeError: Second simultaneous read on fileno 10 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False)

subscribing to ch rfserver<->rfproxy                                        
RFProxy running.
```

I've been running on:
- ryu==2.0
- greenlet==0.4.0 (I also tried updating to 0.4.1)
- eventlet==0.13.0 (Updated as 0.12.1 causes other errors)

**Comment by mzero** [comment]
Hmmm... I'm only on eventlet 0.9.16 and greenlet 0.3.1 - as that is what is on my system already.

I'm also a little down rev of ryu 2.0 --- running at May 22nd's f09407... I'll try pulling this forward and see if it makes a difference.

When I run here I see:

```
-> Starting rftest1ryu
-> Stopping and resetting LXC VMs...
lxc-kill: failed to get the init pid
lxc-kill: failed to get the init pid
lxc-kill: failed to get the init pid
-> Deleting data from previous runs...
-> Setting up the management bridge (lxcbr0)...
-> Starting the rfvm1 virtual machine...
-> Starting the controller and RFPRoxy...
..-> Starting RFServer...
-> Starting the control plane network (dp0 VS)...
-> Starting the sample network...
---
This test is up and running.
Try pinging host b2 from host b1:
  $ sudo lxc-console -n b1
Login and run:
  $ ping 172.31.2.2
You can stop this test by pressing Ctrl+C.
---
^C-> Stopping child processes...
./rftest1ryu: line 45: 14601 Killed                  PYTHONPATH=../ryu:ryu-rfproxy:. ../ryu/bin/ryu-manager --use-stderr --nouse-syslog --ofp-tcp-listen-port $CONTROLLER_PORT --ofp-listen-host localhost ../ryu-rfproxy/rfproxy.py > /var/log/rfproxy.log 2>&1
./rftest1ryu: line 45: 14720 Killed                  PYTHONPATH=. ./rfserver/rfserver.py rftest/rftest1config.csv > /var/log/rfserver.log 2>&1
-> Stopping and resetting LXC VMs...
-> Deleting data from previous runs...
```

And the ping from from the lxc-console works.

On the rfclient for ryu I see:

```
loading app ../ryu-rfproxy/rfproxy.py
loading app ryu.controller.ofp_handler
creating context dpset
instantiating app ../ryu-rfproxy/rfproxy.py
subscribing to ch rfserver<->rfproxy
RFProxy running.
instantiating app ryu.controller.ofp_handler
Datapath is up (dp_id=7266767372667673)
send on ch rfserver<->rfproxy to rfserver:
DatapathPortRegister
  ct_id: 0x0
  dp_id: 0x7266767372667673
  dp_port: 1

Registering datapath port (dp_id=7266767372667673,dp_port=1)
send on ch rfserver<->rfproxy to rfserver:
DatapathPortRegister
  ct_id: 0x0
  dp_id: 0x7266767372667673
  dp_port: 2

Registering datapath port (dp_id=7266767372667673,dp_port=2)
external send failed, sleeping
Unmapped RFVS port (vs_id=7266767372667673, vs_port=4294967294)
external send succeeded
... and so on ...
```

**Comment by joestringer** [comment]
I rolled back to those versions and the exception disappears. Is this because of a regression in the library, or is the library now more smart about detecting this potential error condition?

I hit some snags trying to narrow down which version introduces the exception.

**Comment by joestringer** [comment]
Oh, this needs signoff too.

**Comment by mzero** [comment]
added Signed-off-by to commit

**Comment by joestringer** [comment]
Thanks! I've merged this with the following incremental pep8 style fixups:

```
--- a/rfproxy.py                                                                                                                                                                
+++ b/rfproxy.py
@@ -67,11 +67,12 @@ class Table:
     # If a packet comes and matches the invalid mapping, it can be redirected
     # to the wrong places. We have to fix this.

+
 class HubThreading(object):
-  Thread = staticmethod(threading.Thread)
-  Event = staticmethod(hub.Event)
-  sleep = staticmethod(hub.sleep)
-  name = "HubThreading"
+    Thread = staticmethod(threading.Thread)
+    Event = staticmethod(hub.Event)
+    sleep = staticmethod(hub.sleep)
+    name = "HubThreading"


 # IPC message Processing
```

**Pull request closed without merging**
